<?php

/**
 * @file
 * Code for the GT content types feature.
 */
include_once 'gt_content_types.features.inc';

/**
 * Implements hook_theme_registry_alter()
 */
function gt_content_types_theme_registry_alter(&$theme_registry) {
  /* Fix to mymodule issue
   * from https://www.drupal.org/docs/7/creating-custom-modules/howtos/using-template-tplphp-files-in-your-own-module
   */
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'gt_content_types');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
